site = 'http://my-db.leadgid.space/affiliate/spystore/'
login = 'e.dubitskaya@leadgid.ru'
password = 'Wolfy023'
try_admin_logined = 'Войти как партнёр'
passed_admin_login = "Залогинились"
failed_admin_login = "Скорее всего уже админ залогинен или что-то сломалось"
try_partner_logined = 'Ваши баллы по конкурсу Миссия: Panamera'
passed_partner_login = "Вошли в ЛК партнера № 30003"
failed_partner_login = "Где-то упало на этапе входа в партнера"
passed_shop_popup = 'Боковая панель магазина отображается'
failed_shop_popup = 'Что-то не так с панелью магазина'
